stages:
  - run

image:
  name: registry.gitlab.com/torese/docker-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRRTER: /usr/bin/python3

before_script:
  - yum install httpd curl -y
  - yum install -y python3
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mkdir -p ~/.local/bin
  - mv ./kubectl ~/.local/bin/kubectl
   # and then append (or prepend) ~/.local/bin to $PATH
  - kubectl version
  - echo -n $KUBE_CONFIG | base64 -d > ./config
  - ansible --version

run:
  stage: run
  script:
    - ansible-playbook gitlab/deploy_app.yml
