stages:
  - run

image:
  name: williamyeh/ansible:ubuntu18.04

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRRTER: /usr/bin/python3

run:
  stage: run
  script:
    - pip install boto boto3 netaddr passlib
    - apt install -y curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mkdir -p ~/.local/bin
    - mv ./kubectl ~/.local/bin/kubectl
    # and then append (or prepend) ~/.local/bin to $PATH
    - kubectl version
    - echo -n $KUBE_CONFIG | base64 -d > ./config
    - ansible-playbook gitlab/deploy_app.yml
