stages:
  - run

image:
  name: williamyeh/ansible:ubuntu18.04
  
variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRRTER: /usr/bin/python3
    KUBE_CONFIG: $KUBE_CONFIG64

run:
  stage: run
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 54.195.157.185 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  environment:
    name: production
  script:
    - pip install boto boto3 netaddr passlib
    - apt -y update && apt-get install -y apt-transport-https ca-certificates curl
    - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
    - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - apt-get update && apt-get install -y kubectl
    - mkdir ~/.kube/
    - echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
    - kubectl version
    - ssh-keygen
    - cat 
    - echo -e "[master]\n172.17.0.1" | tee -a /etc/ansible/hosts
    - ansible-playbook gitlab/deploy-app.yml
