- hosts: all
  #don't fail and keep proceeding
  gather_facts: false
  max_fail_percentage: 0
  tasks:
  - name: deploy app deployment
    k8s:
      state: present
      src: /opt/k8s/regapp-deploy.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
